name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Jalankan setiap hari pada tengah malam
  workflow_dispatch:  # Memungkinkan untuk menjalankan workflow secara manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jhesayaa
          svg_out_path: dist/github-contribution-grid-snake.svg
          svg_out_path_dark: dist/github-contribution-grid-snake-dark.svg
      
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output  # Cabang khusus untuk output
          force_orphan: true  # Memastikan cabang output hanya memiliki commit terbaru
